### ISSUE TITLE
Hello, may I ask when I can read your paper?

### ISSUE THREAD

**Issue by houjie8888** [ppanzx/CHAN#1]
It seems that there is currently no place to download the paper.

**Comment by beshining** [comment]
Very nice work! Will you open-source the training code and models?

**Comment by beshining** [comment]
> It seems that there is currently no place to download the paper.
here it is.
https://openaccess.thecvf.com/content/CVPR2023/papers/Pan_Fine-Grained_Image-Text_Matching_by_Cross-Modal_Hard_Aligning_Network_CVPR_2023_paper.pdf
