### ISSUE TITLE
Problems with the data set

### ISSUE THREAD

**Issue by 569337083** [ppanzx/CHAN#3]
I verify the test set, the feature of the picture is [5000, 36,2048], I need to design a test set by myself, and convert a picture to [36,2048], what should I do?

**Comment by ppanzx** [comment]
Before feeding your image to our model, it is necessary to preprocess it using BUTD-based Faster RCNN. This preprocessing step involves extracting the features of salient regions using the implementation available at https://github.com/MILVLG/bottom-up-attention.pytorch.git.
